docs/vpn.md

VPN sayfası, hizmet olarak Mullvad önerisi.

VPN sayfası

---

index.html

- Implemented a toggle switch at the bottom right corner.
- Added functionality to switch themes and update site
- Click the switch to toggle between light and dark modes.

Add Light/Dark Mode Switch Button

---

CONTRIBUTING.md

Katkı sağlamak isteyeneler için dokümantasyon, eklemeler yapılacak.

Katkı sağlama hakkında dokümentasyon

---

index.html

Örnek;
1. Parametre: Dökümanların olduğu link
2. Parametre: İlgili sayfa (ilk parametreye göre otomatik ayarlanır)
3. Parametre: Button'un text'i
```code
plugins: [
EditOnGithubPlugin.create(
"https://github.com/GokturkTalha/guvendekal.org/tree/main/docs/", 
"",
"✏️ Github'da Düzenle")
]
```

Add a redirect button to the Github to edit the page

---

index.html

Add bottom pagination

---

docs/README.md

- Ungoogled Chromium tarayıcısı, Başlangıç sayfasında bulunan "İnternet Tarayıcıları" sekmesine eklendi.

Önerilen Uygulamalar Eklemesi

---

docs/tarayici-eklentileri.md

- Tarayıcı eklentileri kısmındaki markdown ve yazım hataları düzeltildi.

Markdown ve yazım hataları düzeltmesi.

---

docs/posta-servisleri.md

Bu kısmı böyle yazarsak daha iyi olacaktır...

docs: posta-servisleri.md

---

docs/internet-tarayicilari.md

- Firefox'un herhangi bir ayar yapılmadanki halinin barındırdığı güvenlik/gizlilik ihlallerini içeren bir ileri okuma makalesi eklendi.
Bu makaleye bilgi olması açısından eklemenin iyi olacağı düşüncesindeyim. Firefox'u daha güvenli bir hale getirirken oldukça faydalı oldu. Ayrıca makalenin kendi içerisinde de ileri okuma yapılabilecek bazı linkler mevcut.

Firefox için ileri okuma makalesi eklendi.

---

index.html

Docsify resmi olarak [full text search](https://docsify.js.org/#/plugins?id=full-text-search) özelliği olan bir arama eklentisi sağlıyor. Dökümantasyon büyüdükçe kullanıcıların aradığı bir özellik olacak. Eğer ileriye dönük özel bir plan yoksa şimdiden eklememizde fayda var.

Docsify'a arama yapma özelliğinin eklenmesi

---

index.html

Sayfa değiştirirken kaydırmanın en üste sıfırlanmasını sağlandı. Önceki durumda, bir sayfayı en altta iken diğerine geçtiğimizde alttan devam ediyordu. Artık her yeni sayfa açıldığında yukarıdan başlıyor.

Sayfa değişiminde en üste kaydırma özelliği eklendi

---

.vscode/terminals.json
docs/dns.md

Bazı internet servis sağlayıcıları DNS değişikliklerini etkilediği biliniyor. Bu konuda bir uyarı yazısı eklenmiştir.

DNS değişiklikleri için ISS uyarısı eklenmesi

---

.prettierrc

Projede .prettierrc dosyası bulunmuyor. Herkesin prettier ve formatting ayarları farklı olabilir. Her index.html ve benzeri dosyalar değiştiğinde farklı formatta dosyalar commitlenebilir. Tutarlılığı koruması amacıyla .prettierrc dosyası eklenmiştir.

.prettierrc dosyasının eklenmesi

---

docs/2-faktorlu-dogrulama.md

Eğer yine bir hata ya da eksiklik bulursanız lütfen bana belirtin gözümden kaçmış olabilir.

2FA hataları düzeltildi

---

docs/sifre-yoneticileri.md

MD5 veya türevi hashing fonksiyonları tek yönlü metotlardır, hashlenmemiş veriye geri dönüş yapılmaz ve hashing bir şifreleme metotu olarak kullanılamaz.
Örnek şifreleme fonksiyonu: https://github.com/dokuzKey/thencrypt/blob/main/src/utils/encryption.ts
Örnek hashleme fonksiyonu: https://github.com/dokuzKey/thencrypt/blob/main/src/utils/hashing.ts

Hatalı bilgi düzeltmesi

---

docs/katkida-bulunanlar.md
docs/tarayici-eklentileri.md
style.css

Eklenti linkleri eklendi

---

docs/rss-istemcileri.md

FreshRSS istemcisinin açıklaması yazıldı.

FreshRSS-yazısı-eklendi.md

---

docs/rss-istemcileri.md

miniflux-eklendi-rss-istemcileri.md

---

docs/rss-istemcileri.md

Fluent Reader RSS istemcisi listeye eklendi.

Fluent-Reader-eklendi-rss-istemcileri.md

---

docs/README.md

Başlangıç sayfasında yer alan yazılımlara Fluent Reader da eklendi.

Başlangıç-RSS-İstemcileri-Fluent-Reader-Eklendi-README.md

---

docs/android.md

Android sayfasına Linksheet eklendi

---

docs/sosyal-aglar.md

Odysee platformu sosyal medya sayfasına eklendi

odysee-eklendi-sosyal-aglar.md

---

docs/tarayici-eklentileri.md

#152 'de önerilen eklenti eklendi

Tosdr eklentisi eklendi

---

.github/workflows/publish_pages.yml
.gitignore
CNAME

Hem main hem de develop için elle CNAME dosyası ekleyip bunu da gitignore ile PR'lar arasında dikkate alınmayacak şekle getirirsek sanırım sorun çözülecek.

CNAME dosyası eklendi. Workflow güncellendi.

---

docs/sozluk.md

Sözlüğe 2 yeni terim eklendi.
Sözlükteki "A" harfi altındaki terimler alfabetik sıraya göre sıralandı.

Sözlük ekleme ve düzeltme

---

docs/windows-guvenligi.md

Winutil eklendi. Logo bulamadığım için eklemedim
_Uygun olan kutulara `x` işareti koyun._
_Uygun olan kutulara `x` işareti koyun._ Bunları PR oluşturduktan sonra da doldurabilirsiniz. Bunlardan herhangi biri hakkında emin değilseniz, sormaktan çekinmeyin. Yardım etmek için buradayız! Bu sadece kodunuzu birleştirmeden önce nelere bakacağımıza dair bir hatırlatmadır._

Windows güvenliği kısmına winutil eklendi.

---

docs/README.md
docs/torrent-istemcileri.md

WebTorrent ve WebTorrent Desktop açıklamaları eklendi.
Uygun olan kutulara `x` işareti koyun.
Uygun olan kutulara `x` işareti koyun. Bunları PR oluşturduktan sonra da doldurabilirsiniz. Bunlardan herhangi biri hakkında emin değilseniz, sormaktan çekinmeyin. Yardım etmek için buradayız! Bu sadece kodunuzu birleştirmeden önce nelere bakacağımıza dair bir hatırlatmadır.
Repo'ya en son resim eklenmiyordu o yüzden denemedim, pr kabul ederseniz resim kısmını size takdim ediyorum hocalarım.

WebTorrent eklendi.

---

docs/2-faktorlu-dogrulama.md
docs/android-guvenligi.md
docs/dns.md

Lütfen yaptığınız değişikleri önizleme olması açısından kısaca açıklayınız. Yaptığınız değişiklikler bir hatayı düzeltiyorsa veya bir özellik talebini çözüyorsa, bu soruna bağlantı verdiğinizden emin olun.
Uygun olan kutulara `x` işareti koyun.
Uygun olan kutulara `x` işareti koyun. Bunları PR oluşturduktan sonra da doldurabilirsiniz. Bunlardan herhangi biri hakkında emin değilseniz, sormaktan çekinmeyin. Yardım etmek için buradayız! Bu sadece kodunuzu birleştirmeden önce nelere bakacağımıza dair bir hatırlatmadır.
Ekleme yapmak istediğiniz diğer konuları buraya yazabilirsiniz..

Yazım yanlışı ve cümle yapısı düzeltmeleri

---

docs/dosya-donusturme.md
docs/kriterler.md

Lütfen yaptığınız değişikleri önizleme olması açısından kısaca açıklayınız. Yaptığınız değişiklikler bir hatayı düzeltiyorsa veya bir özellik talebini çözüyorsa, bu soruna bağlantı verdiğinizden emin olun.
Uygun olan kutulara `x` işareti koyun.
Uygun olan kutulara `x` işareti koyun. Bunları PR oluşturduktan sonra da doldurabilirsiniz. Bunlardan herhangi biri hakkında emin değilseniz, sormaktan çekinmeyin. Yardım etmek için buradayız! Bu sadece kodunuzu birleştirmeden önce nelere bakacağımıza dair bir hatırlatmadır.
Ekleme yapmak istediğiniz diğer konuları buraya yazabilirsiniz..

Yazım yanlışı

---

docs/sifre-yoneticileri.md

Lütfen yaptığınız değişikleri önizleme olması açısından kısaca açıklayınız. Yaptığınız değişiklikler bir hatayı düzeltiyorsa veya bir özellik talebini çözüyorsa, bu soruna bağlantı verdiğinizden emin olun.
Uygun olan kutulara `x` işareti koyun.
Uygun olan kutulara `x` işareti koyun. Bunları PR oluşturduktan sonra da doldurabilirsiniz. Bunlardan herhangi biri hakkında emin değilseniz, sormaktan çekinmeyin. Yardım etmek için buradayız! Bu sadece kodunuzu birleştirmeden önce nelere bakacağımıza dair bir hatırlatmadır.
Ekleme yapmak istediğiniz diğer konuları buraya yazabilirsiniz..

Şifre yöneticileri kısmında sunucu tarafı kaynak koduna değinildi
